name: Start EC2 Instance 

on:
  push:
    branches:
      - main 

env:
  AWS_REGION: 'us-east-2' 
  INSTANCE_ID: 'i-0ccc30222b0b4ff2b'

jobs:
  start-ec2-instance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start EC2 Instance
        id: start-instance
        run: |
          aws ec2 start-instances --instance-ids ${{ env.INSTANCE_ID }}
        continue-on-error: true

      - name: Check for Error
        if: steps.start-instance.outcome == 'failure'
        run: echo "Failed to start instance. Check AWS permissions and instance details."


