name: Start EC2 Instance 

on:
  push:
    branches:
      - main 

env:
  AWS_REGION: 'us-east-2' 
  INSTANCE_ID: 'i-0ccc30222b0b4ff2b'

jobs:
  start-ec2-instance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-18-226-177-152.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts
          ssh -vvv -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@ec2-18-226-177-152.us-east-2.compute.amazonaws.com echo "SSH Test Successful"

